"""empty message

Revision ID: 1f18e0a7714c
Revises: 95869f037cb7
Create Date: 2020-07-23 13:51:14.191107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f18e0a7714c'
down_revision = '95869f037cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orginizer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('trip', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trip', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_column('trip', 'user_id')
    op.drop_table('partner')
    op.drop_table('orginizer')
    # ### end Alembic commands ###
