"""empty message

Revision ID: 4314f8235f5f
Revises: 5618bbe5f335
Create Date: 2020-07-25 16:29:20.003079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4314f8235f5f'
down_revision = '5618bbe5f335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner')
    op.drop_table('organizer')
    op.add_column('user', sa.Column('percent', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('rate', sa.Integer(), nullable=True))
    op.drop_index('ix_user_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_name', 'user', ['name'], unique=1)
    op.drop_column('user', 'rate')
    op.drop_column('user', 'percent')
    op.create_table('organizer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('partner',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('rate', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
